# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sans-reduce-gui.ui'
#
# Created: Mon Jul  5 10:06:11 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_sansReduceUI(object):
    def setupUi(self, sansReduceUI):
        sansReduceUI.setObjectName("sansReduceUI")
        sansReduceUI.resize(550, 400)
        self.frame = QtGui.QFrame(sansReduceUI)
        self.frame.setGeometry(QtCore.QRect(20, 60, 511, 191))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtGui.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 451, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sansRunLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.sansRunLabel.setObjectName("sansRunLabel")
        self.gridLayout.addWidget(self.sansRunLabel, 2, 0, 1, 1)
        self.transLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.transLabel.setObjectName("transLabel")
        self.gridLayout.addWidget(self.transLabel, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.sampleLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.sampleLabel.setObjectName("sampleLabel")
        self.gridLayout.addWidget(self.sampleLabel, 0, 1, 1, 1)
        self.sansRunMenu = QtGui.QComboBox(self.gridLayoutWidget)
        self.sansRunMenu.setObjectName("sansRunMenu")
        self.gridLayout.addWidget(self.sansRunMenu, 2, 1, 1, 1)
        self.sansTransMenu = QtGui.QComboBox(self.gridLayoutWidget)
        self.sansTransMenu.setObjectName("sansTransMenu")
        self.gridLayout.addWidget(self.sansTransMenu, 3, 1, 1, 1)
        self.bgdLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.bgdLabel.setObjectName("bgdLabel")
        self.gridLayout.addWidget(self.bgdLabel, 0, 2, 1, 1)
        self.bgdRunMenu = QtGui.QComboBox(self.gridLayoutWidget)
        self.bgdRunMenu.setObjectName("bgdRunMenu")
        self.gridLayout.addWidget(self.bgdRunMenu, 2, 2, 1, 1)
        self.bgdTransMenu = QtGui.QComboBox(self.gridLayoutWidget)
        self.bgdTransMenu.setObjectName("bgdTransMenu")
        self.gridLayout.addWidget(self.bgdTransMenu, 3, 2, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(100, 120, 301, 62))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.showRawCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.showRawCheckbox.setChecked(True)
        self.showRawCheckbox.setObjectName("showRawCheckbox")
        self.gridLayout_2.addWidget(self.showRawCheckbox, 0, 0, 1, 1)
        self.showNexusCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.showNexusCheckbox.setObjectName("showNexusCheckbox")
        self.gridLayout_2.addWidget(self.showNexusCheckbox, 1, 0, 1, 1)
        self.maskFilePushButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.maskFilePushButton.setObjectName("maskFilePushButton")
        self.gridLayout_2.addWidget(self.maskFilePushButton, 0, 1, 1, 1)
        self.directBeamRunMenu = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.directBeamRunMenu.setObjectName("directBeamRunMenu")
        self.directBeamRunMenu.addItem("")
        self.gridLayout_2.addWidget(self.directBeamRunMenu, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(sansReduceUI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inPathPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.inPathPushButton.setObjectName("inPathPushButton")
        self.horizontalLayout.addWidget(self.inPathPushButton)
        self.inPathLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.inPathLineEdit.setObjectName("inPathLineEdit")
        self.horizontalLayout.addWidget(self.inPathLineEdit)
        self.reducePushButton = QtGui.QPushButton(sansReduceUI)
        self.reducePushButton.setGeometry(QtCore.QRect(370, 360, 141, 32))
        self.reducePushButton.setObjectName("reducePushButton")
        self.queueReductionsCheckbox = QtGui.QCheckBox(sansReduceUI)
        self.queueReductionsCheckbox.setGeometry(QtCore.QRect(370, 340, 141, 21))
        self.queueReductionsCheckbox.setObjectName("queueReductionsCheckbox")
        self.cancelPushButton = QtGui.QPushButton(sansReduceUI)
        self.cancelPushButton.setGeometry(QtCore.QRect(240, 360, 115, 32))
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.gridLayoutWidget_3 = QtGui.QWidget(sansReduceUI)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 260, 511, 71))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.outputLOQCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.outputLOQCheckbox.setObjectName("outputLOQCheckbox")
        self.gridLayout_3.addWidget(self.outputLOQCheckbox, 0, 0, 1, 1)
        self.outputCanSASCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.outputCanSASCheckbox.setChecked(True)
        self.outputCanSASCheckbox.setObjectName("outputCanSASCheckbox")
        self.gridLayout_3.addWidget(self.outputCanSASCheckbox, 1, 0, 1, 1)
        self.blogReductionCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.blogReductionCheckbox.setObjectName("blogReductionCheckbox")
        self.gridLayout_3.addWidget(self.blogReductionCheckbox, 1, 1, 1, 1)
        self.useRunnumberCheckbox = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.useRunnumberCheckbox.setChecked(True)
        self.useRunnumberCheckbox.setObjectName("useRunnumberCheckbox")
        self.gridLayout_3.addWidget(self.useRunnumberCheckbox, 0, 2, 1, 1)
        self.outPathPushButton = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outPathPushButton.sizePolicy().hasHeightForWidth())
        self.outPathPushButton.setSizePolicy(sizePolicy)
        self.outPathPushButton.setObjectName("outPathPushButton")
        self.gridLayout_3.addWidget(self.outPathPushButton, 1, 2, 1, 1)

        self.retranslateUi(sansReduceUI)
        QtCore.QMetaObject.connectSlotsByName(sansReduceUI)

    def retranslateUi(self, sansReduceUI):
        sansReduceUI.setWindowTitle(QtGui.QApplication.translate("sansReduceUI", "SANS 1D Reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.sansRunLabel.setText(QtGui.QApplication.translate("sansReduceUI", "SANS Run", None, QtGui.QApplication.UnicodeUTF8))
        self.transLabel.setText(QtGui.QApplication.translate("sansReduceUI", "Transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleLabel.setText(QtGui.QApplication.translate("sansReduceUI", "Sample Run", None, QtGui.QApplication.UnicodeUTF8))
        self.bgdLabel.setText(QtGui.QApplication.translate("sansReduceUI", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.showRawCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Show RAW", None, QtGui.QApplication.UnicodeUTF8))
        self.showNexusCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Show Nexus", None, QtGui.QApplication.UnicodeUTF8))
        self.maskFilePushButton.setText(QtGui.QApplication.translate("sansReduceUI", "Mask file...", None, QtGui.QApplication.UnicodeUTF8))
        self.directBeamRunMenu.setItemText(0, QtGui.QApplication.translate("sansReduceUI", "Direct Beam Run", None, QtGui.QApplication.UnicodeUTF8))
        self.inPathPushButton.setText(QtGui.QApplication.translate("sansReduceUI", "File Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.reducePushButton.setText(QtGui.QApplication.translate("sansReduceUI", "Reduce", None, QtGui.QApplication.UnicodeUTF8))
        self.queueReductionsCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Queue reductions", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelPushButton.setText(QtGui.QApplication.translate("sansReduceUI", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLOQCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Output LOQ format", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCanSASCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Output CanSAS 1D", None, QtGui.QApplication.UnicodeUTF8))
        self.blogReductionCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", "Blog reduction...", None, QtGui.QApplication.UnicodeUTF8))
        self.useRunnumberCheckbox.setText(QtGui.QApplication.translate("sansReduceUI", " Output name is run #", None, QtGui.QApplication.UnicodeUTF8))
        self.outPathPushButton.setText(QtGui.QApplication.translate("sansReduceUI", "Output directory...", None, QtGui.QApplication.UnicodeUTF8))

